alias c="cd"
alias cc="clang"
alias copy="xclip -selection clipboard"
alias chmox="chmod +x "
alias ddg="ddgr -x -n 5"
alias g="git"
alias info="info --vi-keys"
alias l="ls"
alias la="ls -la"
alias ls="ls --color=auto"
alias o="xdg-open "
alias open="xdg-open "
alias py="python3"
alias s="sudo "
alias sl="ls "
alias sudo="sudo " # makes aliases work with sudo
alias v="vim "
alias x="tar xzvf"
alias todo="vim ~/todo"
alias mktrans="sh -c 'xprop -f _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY $(printf 0x%x $((0xffffffff * 80 / 100)))'"
source ~/.variables
